from __future__ import annotations

APP_NAME = "PAS"
APP_SUBTITLE = "Performance Analysis System — Hellas Verona 2025-26"

SEASON_PHASES_2526 = ["Pre Season", "In Season"]

PLAYERS_HELLAS = [
    "AJAYI JUNIOR",
    "AKPA AKPRO JEAN-DANIEL",
    "AL-MUSRATI MOATASEM",
    "BELGHALI RAFIK",
    "BELLA KOTCHAP ARMEL",
    "BERNEDE ANTOINE",
    "BRADARIC DOMAGOJ",
    "FALLOU CHAM",
    "DE BATTISTI DAVIDE",
    "EBOSSE ENZO",
    "GAGLIARDINI ROBERTO",
    "GIOVANE SANTANA DO NASCIMENTO",
    "HARROUI ABDOU",
    "KASTANOS GRIGORIS",
    "MOSQUERA DANIEL",
    "NELSSON VICTOR",
    "NIASSE CHEIKH",
    "NUNEZ UNAI",
    "ORBAN GIFT",
    "SARR AMIN",
    "SERDAR SUAT",
    "SLOTSAGER TOBIAS",
    "SUSLOV TOMAS",
    "SZIMIONAS LUCA",
    "VALENTINI NICHOLAS",
    "VERMESAN IOAN",
    "YELLU SANTIAGO",
    "FRESE MARTIN",
    "OYEGOKE DANIEL",
    "LIROLA POL",
    "ISAAC TOMICH",
    "LOVRIC SANDI",
    "BOWIE KIERON",
    "EDMUNDSSON ANDRIAS",
]

METRICS = {
    "RPE": {
        "color": "#9C6ADE",
        "column": "RPE (CR10)",
        "unit": "",
        "aggregation": "mean",
        "accumulation": "mean",
        "decimals": 1,
        "format": "number",
    },
    "Anaerobic Threshold Zone (mm:ss)": {
        "color": "#D45087",
        "column": "Anaerobic threshold zone (hh:mm:ss)",
        "unit": "mm:ss",
        "aggregation": "sum",
        "accumulation": "sum",
        "decimals": 0,
        "format": "duration",
    },
    "High Intensity Training (mm:ss)": {
        "color": "#E76F51",
        "column": "High intensity training (hh:mm:ss)",
        "unit": "mm:ss",
        "aggregation": "sum",
        "accumulation": "sum",
        "decimals": 0,
        "format": "duration",
    },
    "Duration (min)": {
        "color": "#6C8EBF",
        "column": "Duration (dec)",
        "unit": "min",
        "aggregation": "sum",
        "accumulation": "sum",
        "decimals": 0,
        "format": "number",
    },
    "Distance (m)": {
        "color": "#4C78A8",
        "column": "distance (m)",
        "unit": "m",
        "aggregation": "sum",
        "accumulation": "sum",
        "decimals": 0,
        "format": "number",
    },
    "Distance 19.8-25.2 km/h (m)": {
        "color": "#F2CF5B",
        "column": "distance/speed Z3 (m)",
        "unit": "m",
        "aggregation": "sum",
        "accumulation": "sum",
        "decimals": 0,
        "format": "number",
    },
    "Distance >25.2 km/h (m)": {
        "color": "#E45756",
        "column": "distance/speed Z4 (m)",
        "unit": "m",
        "aggregation": "sum",
        "accumulation": "sum",
        "decimals": 0,
        "format": "number",
    },
    "Acc Events (n°)": {
        "color": "#54A24B",
        "column": "acc events",
        "unit": "n°",
        "aggregation": "sum",
        "accumulation": "sum",
        "decimals": 0,
        "format": "number",
    },
    "Dec Events (n°)": {
        "color": "#F58518",
        "column": "dec events",
        "unit": "n°",
        "aggregation": "sum",
        "accumulation": "sum",
        "decimals": 0,
        "format": "number",
    },
    "Max Speed (km/h)": {
        "color": "#B279A2",
        "column": "max speed (km/h)",
        "unit": "km/h",
        "aggregation": "max",
        "accumulation": "max",
        "decimals": 1,
        "format": "number",
    },
    "Speed Events (n°)": {
        "color": "#72B7B2",
        "column": "speed events",
        "unit": "n°",
        "aggregation": "sum",
        "accumulation": "sum",
        "decimals": 0,
        "format": "number",
    },
}

DEFAULT_DRILLS = [
    "Full Training",
    "Different Training",
    "Gym + Field Session",
    "Match",
    "Friendly Match",
    "Individual Training",
    "Return to Play",
    "Active Recovery",
]
